language: php

php:
  - 5.4
  - 5.5

notifications:
  email: false
  slack:
    secure: D1mVD8JQIf4wolRVOVfQ6Eex9kVc6FZqKPlx9GFS3JGOAa52dfe64ruGRT4b64xIJv6QDq/jl92hDnLD/+m5+Yl9/vxlXIm/cBOkl3LTVmNXKV/hWbKXUrob1pwMabv2Q1zA0IcgnwGRO9DGlnV2YtnHWvkNNYpj/2Ry2eC4C+k=

install:
  - composer selfupdate
  - composer install --no-interaction

before_script:
  - mkdir -p build/logs
  - mysql -e 'create database `OpenBuildings/site-versions`;'
  - mysql --default-character-set=utf8 OpenBuildings/site-versions < tests/test_data/structure.sql

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
